// app/renderer/ui/components/walletForm/steps/walletEncryptionPassword/index.tsx
import * as React from "react"

import { NavigationCard } from "app/renderer/ui/components/card"
import { InputUnderlined } from "app/renderer/ui/components/input"

const stepStyles = require("./style.scss")
const commonFormStepStyles = require("app/renderer/ui/components/walletForm/steps/style.scss")

export interface WalletEncryptionPasswordProps {
  className?: string,
  errorMessage?: string,
  nextStep: () => void,
  onChangePassword: (ev: React.ChangeEvent) => void,
  onChangeRepeatPassword: (ev: React.ChangeEvent) => void,
  password: string,
  previousStep: () => void,
  repeatPassword: string,
}

/**
 * Step wallet encryption password UI component
 *
 * @export
 * @class WalletEncryptionPassword
 * @extends {React.Component<WalletEncryptionPasswordProps>}
 */
export default class WalletEncryptionPassword extends
  React.Component<WalletEncryptionPasswordProps> {
  /** render */
  public render() {
    const cardStyle = `${commonFormStepStyles.centered} ${this.props.className}`

    return (
      <NavigationCard
        className={cardStyle}
        title="Encrypt your wallet with a password"
        previousStep={this.props.previousStep}
        nextStep={this.props.nextStep}
      >
        <p className={stepStyles.text}>
          <strong>PLEASE NOTE:</strong> this password encrypts your Witnet wallet only on this
          computer. This is not your backup and you cannot restore your wallet with this password.
          Your seed phrase is still your ultimate backup.
        </p>
        <div className={stepStyles.field}>
          <label className={`${stepStyles.label} ${stepStyles["password-label"]}`}>Password</label>
          <InputUnderlined
            className={`${stepStyles.input} ${stepStyles["password-input"]}`}
            type="password"
            onChange={this.props.onChangePassword}
            value={this.props.password}
          />
        </div>
        <div className={stepStyles.field}>
          <label
            className={`${stepStyles.label} ${stepStyles["confirm-password-label"]}`}
          >
            Confirm password
          </label>
          <InputUnderlined
            className={`${stepStyles.input} stepStyles["confirm-password-input"]`}
            type="password"
            onChange={this.props.onChangeRepeatPassword}
            value={this.props.repeatPassword}
          />
        </div>
        <p className={`${commonFormStepStyles.error} ${stepStyles.error}`}>
          {this.props.errorMessage}
        </p>
      </NavigationCard>
    )
  }
}

// src/components/claiming/WalletEncryptionPassword.vue
<template>
  <NavigationCard
    class="wallet-encryption"
    title="Encrypt your wallet with a password"
    previousText="Back"
    nextText="Continue"
    :previousStep="previousStep"
    :nextStep="nextStep"
    ref="navCard"
  >
    <p class="paragraph">
      <strong>PLEASE NOTE:</strong> this password encrypts your Witnet wallet only on this computer.
      This is not your backup and you cannot restore your wallet with this password. Your seed
      phrase is still your ultimate backup.
    </p>
    <div class="form-row password">
      <PasswordInput
        data-test="password-input"
        label="Password"
        v-model="password"
        v-on:go-next="goNextInput"
      />
    </div>
    <div ref="confirm" class="form-row password">
      <PasswordInput
        data-test="password-input"
        ref="password"
        label="Confirm password"
        v-model="repeatPassword"
        v-on:go-next="nextStep"
      />
    </div>
    <div class="form-row">
      <div data-test="password-error-alert" v-if="createValidPasswordError" class="error">
        {{ createValidPasswordError.message }}
      </div>
    </div>
  </NavigationCard>
</template>

<script>
import { mapState } from 'vuex'
import PasswordInput from '@/components/PasswordInput'
import NavigationCard from '@/components/card/NavigationCard'

export default {
  name: 'WalletEncryptionPassword',
  data() {
    return {
      password: '',
      repeatPassword: '',
      error: false,
    }
  },
  watch: {
    password() {
      if (this.createValidPasswordError) {
        this.clearError(this.createValidPasswordError.name)
      }
    },
    repeatPassword() {
      if (this.createValidPasswordError) {
        this.clearError(this.createValidPasswordError.name)
      }
    },
  },
  methods: {
    validateForm() {
      this.$store.commit('validatePassword', {
        password: this.password,
        repeatPassword: this.repeatPassword,
      })
    },
    goNextInput() {
      this.$refs.password.$refs.passInput.focus()
    },
    nextStep() {
      this.validateForm()
      if (this.validatedPassword) {
        if (this.createValidPasswordError) {
          this.clearError(this.createValidPasswordError.name)
        }
        this.$store.dispatch('createWallet', {
          sourceType: 'mnemonics',
          password: this.password,
          mnemonics: this.mnemonics,
        })
        this.$router.push('/claiming/loading')
      }
    },
    previousStep() {
      this.$router.push('/claiming/seed-validation')
    },
    clearError(errorName) {
      this.$store.commit('clearError', { error: errorName })
    },
  },
  computed: {
    ...mapState({
      mnemonics: state => state.wallet.mnemonics,
      createWalletError: state => state.wallet.errors.createWallet,
      createValidPasswordError: state => state.wallet.errors.createValidPassword,
      validatedPassword: state => state.wallet.validatedPassword,
    }),
  },
  components: {
    NavigationCard,
    PasswordInput,
  },
  beforeDestroy() {
    if (this.createValidPasswordError) {
      this.clearError(this.createValidPasswordError.name)
    }
  },
}
</script>
<style lang="scss" scoped>
@import '@/styles/theme.scss';

.error {
  color: $red-0;
  font-size: 14px;
  min-width: 270px;
}

.paragraph {
  margin-top: 16px;
  margin-bottom: 40px;
}

.form-row {
  display: flex;
  max-width: 500px;
  flex-flow: row nowrap;
  margin-bottom: 32px;
  align-items: center;
  justify-content: center;
  &.password {
    max-width: none;
    display: flex;
    flex-flow: row wrap;
    justify-content: center;
  }
}

.label {
  color: $font-color-light;
  width: 100px;
}

.password-input {
  width: 50%;
}
</style>
