// app/renderer/ui/components/walletForm/steps/walletEncryptionPassword/index.tsx
import * as React from "react"

import { NavigationCard } from "app/renderer/ui/components/card"
import { InputUnderlined } from "app/renderer/ui/components/input"

const stepStyles = require("./style.scss")
const commonFormStepStyles = require("app/renderer/ui/components/walletForm/steps/style.scss")

export interface WalletEncryptionPasswordProps {
  className?: string,
  errorMessage?: string,
  nextStep: () => void,
  onChangePassword: (ev: React.ChangeEvent) => void,
  onChangeRepeatPassword: (ev: React.ChangeEvent) => void,
  password: string,
  previousStep: () => void,
  repeatPassword: string,
}

/**
 * Step wallet encryption password UI component
 *
 * @export
 * @class WalletEncryptionPassword
 * @extends {React.Component<WalletEncryptionPasswordProps>}
 */
export default class WalletEncryptionPassword extends
  React.Component<WalletEncryptionPasswordProps> {
  /** render */
  public render() {
    const cardStyle = `${commonFormStepStyles.centered} ${this.props.className}`

    return (
      <NavigationCard
        className={cardStyle}
        title="Encrypt your wallet with a password"
        previousStep={this.props.previousStep}
        nextStep={this.props.nextStep}
      >
        <p className={stepStyles.text}>
          <strong>PLEASE NOTE:</strong> this password encrypts your Witnet wallet only on this
          computer. This is not your backup and you cannot restore your wallet with this password.
          Your seed phrase is still your ultimate backup.
        </p>
        <div className={stepStyles.field}>
          <label className={`${stepStyles.label} ${stepStyles["password-label"]}`}>Password</label>
          <InputUnderlined
            className={`${stepStyles.input} ${stepStyles["password-input"]}`}
            type="password"
            onChange={this.props.onChangePassword}
            value={this.props.password}
          />
        </div>
        <div className={stepStyles.field}>
          <label
            className={`${stepStyles.label} ${stepStyles["confirm-password-label"]}`}
          >
            Confirm password
          </label>
          <InputUnderlined
            className={`${stepStyles.input} stepStyles["confirm-password-input"]`}
            type="password"
            onChange={this.props.onChangeRepeatPassword}
            value={this.props.repeatPassword}
          />
        </div>
        <p className={`${commonFormStepStyles.error} ${stepStyles.error}`}>
          {this.props.errorMessage}
        </p>
      </NavigationCard>
    )
  }
}

// src/components/steps/WalletEncryptionPassword.vue
<template>
  <NavigationCard
    class="wallet-encryption"
    title="Encrypt your wallet with a password"
    previousText="Back"
    nextText="Next"
    :previousStep="previousStep"
    :nextStep="nextStep"
  >
    <div class="content">
      <p class="paragraph">
        <strong>PLEASE NOTE:</strong> this password encrypts your Witnet wallet only on this
        computer. This is not your backup and you cannot restore your wallet with this password.
        Your seed phrase is still your ultimate backup.
      </p>
      <div class="form-row">
        <label class="label">Password</label>
        <Input type="underlined" class="password-input" nativeType="password" v-model="password" />
      </div>
      <div class="form-row">
        <label class="label">Confirm password</label>
        <Input type="underlined" class="password-input" nativeType="password" v-model="repeatPassword" />
      </div>

    </div>
    <p v-if="showError">Password must match</p>
  </NavigationCard>
</template>

<script>
import { mapState } from 'vuex'

import Input from '@/components/Input'
import NavigationCard from '@/components/NavigationCard'

export default {
  name: 'WalletEncryptionPassword',
  data () {
    return {
      password: '',
      repeatPassword: '',
      showError: '',
    }
  },
  methods: {
    nextStep () {
      if (this.password === this.repeatPassword) {
        this.showError = false
        this.$store.dispatch('createWallet', { sourceType: 'mnemonics', password: this.password, mnemonics: this.mnemonics })
        this.$router.push('/ftu/create-wallet')
      } else {
        this.showError = true
      }
    },
    previousStep () {
      this.$router.push('/ftu/seed-validation')
    },
  },
  computed: {
    ...mapState({
      mnemonics: state => state.wallet.mnemonics,
    }),
  },
  components: {
    Input,
    NavigationCard,
  },
}
</script>
<style lang="scss" scoped>
@import '@/styles/theme.scss';

.content {
  padding: 40px;
}

.paragraph {
  margin-top: 10px;
  margin-bottom: 45px;
}

.form-row {
  display: flex;
  max-width: 500px;
  flex-flow: row nowrap;
  margin-bottom: 30px;
  align-items: center;
}

.label {
  color: $font-color-light;
  width: 100px;
}

.password-input {
  width: 50%;

}

</style>
