// src/components/RadonOperator.vue
<template>
 <div class="operator">
    <p>Input Type: {{ inputType }}</p>
    <span>Method: </span>
    <select
      v-model="operatorCode"
      @change="event => updateOperatorCodeSelect(this.path, event.target.value)"
    >
      <option v-for="operatorOption in operatorOptions" :value="operatorOption" :key="operatorOption">
        {{ RadonOperatorInfos[operatorOption].name }}
      </option>
    </select>
    <div class="arguments" v-for="(argValues, index) in RadonOperatorInfos[operatorCode].arguments" :key="argValues.toString() + index"  >

      <div v-if="isTypeOf([RadonTypes.Boolean, RadonTypes.Int, RadonTypes.Float, RadonTypes.String], argValues.kind)">
        <label :htmlFor="argValues.name">
          {{argValues.name}}:
        </label>
        <input
          :name="argValues.name"
          :value="operator[index + 1]"
          @change="event => updateArgumentInput(this.path, event.target.value, operator, index + 1)"
        />
      </div>

      <div v-else-if="isTypeOf(RadonTypes.Map, argValues.kind)">
        <label :htmlFor="argValues.name">
          {{ argValues.name }}:
          </label>
        <input
          :name="argValues.name"
          :value="operator[index + 1]"
          @change="event => updateArgumentInput(this.path, event.target.value, operator, index + 1)"
        />
      </div>

      <div v-else-if="isTypeOf(RadonTypes.HashFunction, argValues.kind)">
          <span>{{argValues.name}}</span>
          <select
            :value="operator[index + 1]"
            @change="event => selectHashFunction(this.path, event.target.value, operator, index + 1)"
          >
            <option v-for="hashCode in hashFunctionCodes" :key="hashCode[0]" :value="hashCode[0]">
              {{ hashCode[1] }}
            </option>
          </select>
      </div>

      <div v-else-if="isTypeOf(RadonTypes.FilterFunction, argValues.kind)">
        <span>{{ argValues.name }}</span>
        <select
          :value="operator[index + 1][0]"
          @change="event => this.updateOperatorFilterArgument(this.props.path, event.target.value, operator, index + 1)"
        >
          <option v-for="(filterCode, index) in filteringFunctionCodes" :key="filteringFunctionCodes[index][1]" :value="filteringFunctionCodes[index][0]">
            {{ filterCode[1] }}
          </option>
        </select>

        <div>
          <span>Value:</span>
          <input
            :value="operator[index + 1][1]"
            @change="event => this.updateFilterArgument(this.path, event.target.value, operator, index + 1)"
          />
        </div>

      </div>

      <div v-else-if="isTypeOf(RadonTypes.ReduceFunction, argValues.kind)">
        <span>{{ argValues.name }}</span>
        <select
          :value="operator[index + 1]"
          @change="event => this.updateOperatorReduceArgument(this.path, event.target.value, operator, index + 1)"
        >
        <option v-for="reducingCode in reducingFunctionCodes" :key="reducingCode[1]">
          {{ reducingCode[1] }}
        </option>
        </select>
      </div>

      <div v-else-if="isTypeOf(RadonTypes.MapFunction, argValues.kind)">
        <label :htmlFor="argValues.name">{{ argValues.name }}*:</label>
        <input
          :name="argValues.name"
          :value="operator[index + 1]"
          @change="event => this.props.updateArgumentInput(this.props.path, event.target.value, operator, index + 1)"
        />
      </div>

    </div>
    <p>Output Type: {{ outputType }}</p>
  </div>
</template>

<script>
import {
  TYPES as RadonTypes,
  TYPESYSTEM as RadonTypeSystem,
  OPERATOR_INFOS as RadonOperatorInfos,
  FilteringFunctionCodes,
  ReducingFunctionCodes,
  HashFunctionCodes,
} from '@/radon'

const DEFAULT_INPUT_TYPE = 0x03

export default {
  name: 'RadonOperator',
  props: {
    radOperator: [Array, Number],
    path: Object,
    selectHashFunction: Function,
    updateArgumentInput: Function,
    updateFilterArgument: Function,
    updateOperatorCodeSelect: Function,
    updateOperatorFilterArgument: Function,
    updateOperatorReduceArgument: Function,
  },
  data () {
    const operatorCode = Array.isArray(this.radOperator) ? this.radOperator[0] : this.radOperator
    const foundType = operatorCode ? this.getTypeFromOperatorCode(operatorCode) : DEFAULT_INPUT_TYPE
    const inputType = RadonTypes[foundType]
    const operator = Array.isArray(this.radOperator) ? this.radOperator : [this.radOperator]
    const outputType = RadonTypes[RadonTypeSystem[foundType][operatorCode]]
    const operatorOptions = Object.keys(RadonTypeSystem[RadonTypes[inputType]])
    return {
      inputType,
      operator,
      operatorCode,
      operatorOptions,
      outputType,
    }
  },
  computed: {
    hashFunctionCodes: function () {
      return Object.entries(HashFunctionCodes)
        .slice(0, Object.entries(HashFunctionCodes).length / 2)
    },
    filteringFunctionCodes: function () {
      return Object.entries(FilteringFunctionCodes)
        .slice(0, Object.entries(FilteringFunctionCodes).length / 2)
    },
    reducingFunctionCodes: function () {
      return Object.entries(ReducingFunctionCodes)
        .slice(0, Object.entries(ReducingFunctionCodes).length / 2)
    },
    RadonOperatorInfos: function () {
      return RadonOperatorInfos
    },
    RadonTypes: function () {
      return RadonTypes
    },
  },

  methods: {
    isTypeOf (types, candidate) {
      return Array.isArray(types)
        ? types.includes(candidate)
        : types === candidate
    },
    getTypeFromOperatorCode: function (operatorCode) {
      const result = Object.entries(RadonTypeSystem)
        .reduce((acc, array) => {
          const hasSameType = Object.keys(array[1]).find(code => {
            return parseInt(code) === operatorCode
          })
          if (hasSameType) {
            acc = array[0]
          }
          return acc
        }, '')
      return result
    },
  },
}
</script>

<style>
.operator {
  border: 1px solid black;
}
</style>

// app/renderer/ui/components/radonOperator/index.tsx
import * as React from "react"

import {
  TYPES as RadonTypes,
  TYPESYSTEM as RadonTypeSystem,
  OPERATOR_INFOS as RadonOperatorInfos,
  FilteringFunctionCodes,
  ReducingFunctionCodes,
  HashFunctionCodes,
  TYPES,
} from "../../../radon"
import { match } from "app/renderer/utils/match"

const styles = require("./style.scss")

export interface RadonOperatorProps {
  path: {
    scriptIndex: number,
    stage: "retrieve" | "aggregate" | "consensus",
  },
  operator: Array<any> | number,
  updateOperatorCodeSelect: Function,
  updateOperatorFilterArgument: Function,
  updateFilterArgument: Function,
  updateOperatorReduceArgument: Function,
  selectHashFunction: Function,
  updateArgumentInput: Function,

}

export interface RadonOperatorState {
  inputType: string,
  operator: Array<any>,
  outputType: string,
}

/**
 * RadonOperator ui component
 *
 * @export
 * @class RadonOperator
 * @extends {React.Component<RadonOperatorProps>}
 */
export default class RadonOperator extends React.Component<RadonOperatorProps, RadonOperatorState> {
  private getTypeFromOperatorCode = (operatorCode: number): string => Object.entries(RadonTypeSystem)
    .reduce((acc, array) => {
      if (Object.keys(array[1]).find(code => parseInt(code) === operatorCode)) {
        acc = array[0]
      }

      return acc
    }, "")

  public render() {
    const operatorCode = Array.isArray(this.props.operator) ? this.props.operator[0] : this.props.operator
    // if there is no operator code default input type is string
    const defaultInputType = 0x03
    const foundType = operatorCode
      ? this.getTypeFromOperatorCode(operatorCode) : defaultInputType

    const inputType = RadonTypes[foundType]
    const operator = Array.isArray(this.props.operator) ? this.props.operator : [this.props.operator]

    const outputType = RadonTypes[RadonTypeSystem[foundType][operatorCode]]

    const operatorOptions = Object.keys(RadonTypeSystem[RadonTypes[inputType]])
      .map((item: string) => <option value={item} key={item}>{RadonOperatorInfos[item].name}</option>)

    return (
      <div className={styles.main}>
        <p>Input Type: {inputType}</p>
        <span>Method: </span>
        <select
          value={operatorCode}
          onChange={
            (e: React.ChangeEvent<HTMLSelectElement>) =>
              this.props.updateOperatorCodeSelect(this.props.path, e.target.value)
          }
        >
          {operatorOptions}
        </select>
        {
          RadonOperatorInfos[operatorCode].arguments
            .map((argValues, index) => {
              return match(argValues.kind, [
                { options: [TYPES.Boolean, TYPES.Int, TYPES.Float, TYPES.String],
                  result: (
                    <div>
                      <label htmlFor={argValues.name}>{argValues.name}:</label>
                      <input
                        name={argValues.name} value={operator[index + 1]}
                        onChange={
                          (e: React.ChangeEvent<HTMLInputElement>) =>
                            this.props.updateArgumentInput(this.props.path, e.target.value, operator, index + 1)
                        }
                      />
                    </div>
                  ),
                },
                {
                  options: [TYPES.Map],
                  result: (
                    <div>
                      <label htmlFor={argValues.name}>{argValues.name}*:</label>
                      <input
                        name={argValues.name} value={operator[index + 1]}
                        onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                          this.props.updateArgumentInput(this.props.path, e.target.value, operator, index + 1)
                        }
                      />
                    </div>
                  ),
                },
                {
                  options: [TYPES.HashFunction],
                  result: (
                    <div>
                      <span>{argValues.name}</span>
                      <select
                        value={operator[index + 1]}
                        onChange={(e: React.ChangeEvent<HTMLSelectElement>) =>
                          this.props.selectHashFunction(this.props.path, e.target.value, operator, index + 1)
                        }
                      >
                        {
                          Object.entries(HashFunctionCodes)
                            .slice(0, Object.entries(HashFunctionCodes).length / 2)
                            .map(item => <option key={item[0]} value={item[0]}>{item[1]}</option>)
                        }
                      </select>
                    </div>),
                },
                {
                  options: [TYPES.FilterFunction],
                  result: (
                    <div>
                      <span>{argValues.name}</span>
                      <select value={operator[index + 1][0]}
                        onChange={(e: React.ChangeEvent<HTMLSelectElement>) =>
                          this.props.updateOperatorFilterArgument(this.props.path, e.target.value, operator, index + 1)
                        }
                      >
                        {Object.entries(FilteringFunctionCodes)
                          .slice(0, Object.entries(FilteringFunctionCodes).length / 2)
                          .map(item => <option key={item[0]} value={item[0]}>{item[1]}</option>)
                        }
                      </select>
                      <div>
                        <span>Value:</span>
                        <input
                          value={operator[index][1]}
                          onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                            this.props.updateFilterArgument(this.props.path, e.target.value, operator, index + 1)
                          }
                        />
                      </div>
                    </div>
                  ),
                },
                {
                  options: [TYPES.ReduceFunction],
                  result: (
                    <div>
                      <span>{argValues.name}</span>
                      <select
                        value={operator[index + 1]}
                        onChange={(e: React.ChangeEvent<HTMLSelectElement>) =>
                          this.props.updateOperatorReduceArgument(this.props.path, e.target.value, operator, index + 1)
                        }
                      >
                        {Object.entries(ReducingFunctionCodes)
                          .slice(0, Object.entries(ReducingFunctionCodes).length / 2)
                          .map(item => <option key={item[0]} value={item[0]}>{item[1]}</option>)
                        }
                      </select>
                    </div>
                  ),
                },
                {
                  options: [TYPES.Self, TYPES.MapFunction],
                  result: (
                    <div>
                      <label htmlFor={argValues.name}>{argValues.name}*:</label>
                      <input
                        name={argValues.name}
                        value={operator[index + 1]}
                        onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                          this.props.updateArgumentInput(this.props.path, e, operator, index + 1)
                        }
                      />
                    </div>
                  ),
                },
              ])
            })
        }

        <p>Output Type: {outputType}</p>
      </div>
    )
  }
}

export {
  RadonOperator,
}
