// src/components/RadonQuery.vue
<template>
  <div class>
    <div>
      <p>Retrieve:</p>
      <textarea
        class="textarea"
        :value="JSON.stringify(retrieve)"
        v-on:keyup.enter="e => updateStage(e, 'retrieve')"
      />
      <p>Aggregate</p>
      <textarea
        class="textarea"
        :value="JSON.stringify(aggregate)"
        v-on:keyup.enter="e => updateStage(e, 'aggregate')"
      />
      <p>Consensus</p>
      <textarea
        class="textarea"
        :value="JSON.stringify(consensus)"
        v-on:keyup.enter="e => updateStage(e, 'consensus')"
      />
    </div>

    <div class>
      <h1>Request</h1>
    </div>
    <div class="row">
      <div v-for="(source, index) in retrieve" class="source" :key="source.kind+index">
        <label>source: {{ index }}</label>
        <input placeholder="url" type="text" v-model="source.url">
        <div>
          <p>Kind:</p>
          <p>{{ source.kind }}</p>
          <div>
            <RadonScript
              v-show="!error.retrieve"
              :path="{stage: 'retrieve', retrieveIndex: index}"
              :script="source.script"
              :updateArgumentInput="updateArgumentInput"
              :selectHashFunction="selectHashFunction"
              :updateFilterArgument="updateFilterArgument"
              :updateOperatorCodeSelect="updateOperatorCodeSelect"
              :updateOperatorFilterArgument="updateOperatorFilterArgument"
              :updateOperatorReduceArgument="updateOperatorReduceArgument"
              :pushOperator="pushOperator"
            />
            <p class="error" v-show="error.retrieve">There is an error in the retrieve stage</p>
          </div>
        </div>
      </div>
      <div class>
        <button v-on:click="pushRetrieve">add source</button>
      </div>
    </div>
    <br>
    <div class>
      <div class>
        <h1>Aggregate</h1>
      </div>
      <div class>
        <div>
          <RadonScript
            v-show="!error.aggregate"
            :path="{stage: 'aggregate'}"
            :script="aggregate.script"
            :updateArgumentInput="updateArgumentInput"
            :selectHashFunction="selectHashFunction"
            :updateFilterArgument="updateFilterArgument"
            :updateOperatorCodeSelect="updateOperatorCodeSelect"
            :updateOperatorFilterArgument="updateOperatorFilterArgument"
            :updateOperatorReduceArgument="updateOperatorReduceArgument"
            :pushOperator="pushOperator"
          />
          <p class="error" v-show="error.aggregate">There is an error in the aggregate stage</p>
        </div>
      </div>
    </div>
    <br>
    <div class>
      <div class>
        <h1>Consensus</h1>
      </div>
      <div class>
        <RadonScript
          v-show="!error.consensus"
          :path="{stage: 'consensus'}"
          :script="consensus.script"
          :updateArgumentInput="updateArgumentInput"
          :selectHashFunction="selectHashFunction"
          :updateFilterArgument="updateFilterArgument"
          :updateOperatorCodeSelect="updateOperatorCodeSelect"
          :updateOperatorFilterArgument="updateOperatorFilterArgument"
          :updateOperatorReduceArgument="updateOperatorReduceArgument"
          :pushOperator="pushOperator"
        />
        <p class="error" v-show="error.consensus">There is an error in the consensus stage</p>
      </div>
    </div>
    <div class>
      <div class>
        <h1>Deliver</h1>
      </div>
      <div class>
        <input placeholder="url">
      </div>
    </div>
  </div>
</template>

<script>

import { match } from '@/utils'
import RadonScript from '@/components/RadonScript.vue'
import {
  TYPES as RadonTypes,
  OPERATOR_INFOS as RadonOperatorInfos,
  TYPESYSTEM as RadonTypeSystem,
  HashFunctionCodes,
  ReducingFunctionCodes,
  FilteringFunctionCodes,
} from '@/radon'

export default {
  name: 'RadonQuery',
  components: {
    RadonScript,
  },
  props: {
    radRequest: Object,
  },
  data () {
    return {
      retrieve: [
        {
          url: '',
          kind: 'HTTP_GET',
          script: [[0x56, 0]],
        },
      ],
      aggregate: {
        script: [0x43, 0x74, [0x61, 'weather'], 0x74, [0x61, 'temp'], 0x72],
      },
      consensus: {
        script: [0x43, 0x74, [0x61, 'weather'], 0x74, [0x61, 'temp'], 0x72],
      },
      error: {
        retrieve: false,
        aggregate: false,
        consensus: false,
      },
    }
  },
  methods: {
    getOutput: function (operatorCode) {
      return Object.entries(RadonTypeSystem).reduce((acc, array) => {
        if (Object.keys(array[1]).find(key => parseInt(key) === operatorCode)) {
          acc = RadonTypes[RadonTypeSystem[array[0]][operatorCode]]
        }
        return acc
      }, '')
    },
    updateStage: function (event, stage) {
      try {
        const result = JSON.parse(event.target.value)
        this[stage] = result
        this.error[stage] = false
      } catch (err) {
        this.error[stage] = true
      }
    },

    getLastOperator: function (request, stage, retrieveIndex) {
      const script = retrieveIndex
        ? this[stage][retrieveIndex].script
        : this[stage].script

      return script[script.length - 1]
    },
    getOperatorCode: function (operator) {
      return Array.isArray(operator) ? operator[0] : operator
    },
    pushOperator: function (path) {
      const { retrieve, aggregate, consensus } = this
      const lastOperator = this.getLastOperator(
        { retrieve, aggregate, consensus },
        path.stage,
        path.retrieveIndex,
      )
      const operatorCode = this.getOperatorCode(lastOperator)
      // const lastOperatorStringType = this.getOutput(operatorCode)
      const operatorsObject =
        RadonTypeSystem[RadonTypes[this.getOutput(operatorCode)]]
      const newOperatorCode = parseInt(Object.entries(operatorsObject)[0][0])
      const newOperatorInfo = RadonOperatorInfos[newOperatorCode]

      // add operator arguments by argument type

      const numberOfOperatorArguments = newOperatorInfo.arguments.length

      if (numberOfOperatorArguments === 0) {
        Number.isInteger(parseInt(path.retrieveIndex))
          ? this[path.stage][path.retrieveIndex].script.push(newOperatorCode)
          : this[path.stage].script.push(newOperatorCode)
      } else {
        // const newOperator = [newOperatorCode, newOperatorInfo.arugments.map(argument => )]
        Number.isInteger(parseInt(path.retrieveIndex))
          ? this[path.stage][path.retrieveIndex].script.push([newOperatorCode])
          : this[path.stage].script.push(newOperatorCode)
      }
    },
    pushRetrieve: function () {
      this.retrieve.push({
        url: '',
        kind: 'HTTP_GET',
        script: [],
      })
    },
    updateArgumentInput: function (path, input, operator, argIndex) {
      operator[argIndex] = input
      if (path.retrieveIndex) {
        this[`${path.stage}`][path.retrieveIndex][path.scriptIndex] = operator
        this[`${path.stage}`] = [...this[`${path.stage}`]]
      } else {
        this[`${path.stage}`][path.scriptIndex] = operator
        this[`${path.stage}`] = { ...this[`${path.stage}`] }
      }
    },
    selectHashFunction: function (path, hashFunctionCode, operator, argIndex) {
      operator[argIndex] = hashFunctionCode
      if (path.retrieveIndex) {
        this[`${path.stage}`][path.retrieveIndex][path.scriptIndex] = operator
        this[`${path.stage}`] = [...this[`${path.stage}`]]
      } else {
        this[`${path.stage}`][path.scriptIndex] = operator
        this[`${path.stage}`] = { ...this[`${path.stage}`] }
      }
    },
    updateOperatorReduceArgument: function (
      path,
      reduceArgument,
      operator,
      argIndex,
    ) {
      operator[argIndex] = reduceArgument
      if (Number.isInteger(path.retrieveIndex)) {
        console.log("---", this[`${path.stage}`])
        this[`${path.stage}`][path.retrieveIndex].script[path.scriptIndex] = operator
        this[`${path.stage}`] = [...this[`${path.stage}`]]
      } else {
        this[`${path.stage}`].script[path.scriptIndex] = operator
        this[`${path.stage}`] = { ...this[`${path.stage}`] }
      }

    },
    updateFilterArgument: function (path, filterArgument, operator, argIndex) {
      operator[argIndex] = [operator[argIndex][0], filterArgument]
      if (path.retrieveIndex) {
        this[`${path.stage}`][path.retrieveIndex][path.scriptIndex] = operator
        this[`${path.stage}`] = [...this[`${path.stage}`]]
      } else {
        this[`${path.stage}`][path.scriptIndex] = operator
        this[`${path.stage}`] = { ...this[`${path.stage}`] }
      }
    },
    updateOperatorFilterArgument: function (
      path,
      filterFunctionCode,
      operator,
      argIndex,
    ) {
      operator[argIndex] = [filterFunctionCode, '']
      if (path.retrieveIndex) {
        this[`${path.stage}`][path.retrieveIndex][path.scriptIndex] = operator
      } else {
        this[`${path.stage}`][path.scriptIndex] = operator
      }
    },
    updateOperatorCodeSelect: function (path, operatorCode) {
      let args = RadonOperatorInfos[operatorCode].arguments.map(argument => {
        console.log("---", operatorCode)
        return match(argument.kind, [
          {
            options: [
              RadonTypes.Boolean,
            ],
            result: true,
          },
          {
            options: [
              RadonTypes.Int,
            ],
            result: 0,
          },
          {
            options: [
            RadonTypes.Float,
            ],
            result: 0.0,
          },
          {
            options: [
              RadonTypes.String,
            ],
            result: "",
          },
          {
            options: [
              RadonTypes.Map,
              RadonTypes.Mixed,
              RadonTypes.Array,
              RadonTypes.Null,
              RadonTypes.Result,
              RadonTypes.Self,
              RadonTypes.MapFunction,
            ],
            result: [],
          },
          {
            options: [RadonTypes.FilterFunction],
            result: [0, 0],
          },
          {
            options: [RadonTypes.HashFunction],
            result: 0,
          },
          {
            options: [RadonTypes.ReduceFunction],
            result: 0,
          },
        ])
      })
      if (path.stage === 'retrieve') {
        this[`${path.stage}`][path.retrieveIndex].script[path.scriptIndex] = [
          parseInt(operatorCode),
          ...args,
        ]
        if (!this.validateRadScript('')) {
          this[`${path.stage}`][path.retrieveIndex].script.splice(
            path.scriptIndex + 1,
            this[`${path.stage}`][path.retrieveIndex].script.length,
          )
        }
        this[`${path.stage}`] = { ...this[`${path.stage}`] }
      } else {
        this[`${path.stage}`].script[path.scriptIndex] = [
          parseInt(operatorCode),
          ...args,
        ]
        if (!this.validateRadScript('')) {
          this[`${path.stage}`].script.splice(
            path.scriptIndex + 1,
            this[`${path.stage}`].script.length,
          )
        }
        this[`${path.stage}`] = { ...this[`${path.stage}`] }
      }
    },
    validateRadScript: function () {
      return false
    },
  },
  computed: {
    hashFunctionCodes: function () {
      return Object.entries(HashFunctionCodes)
        .slice(0, Object.entries(HashFunctionCodes).length / 2)
    },
    filteringFunctionCodes: function () {
      return Object.entries(FilteringFunctionCodes)
        .slice(0, Object.entries(FilteringFunctionCodes).length / 2)
    },
    reducingFunctionCodes: function () {
      return Object.entries(ReducingFunctionCodes)
        .slice(0, Object.entries(ReducingFunctionCodes).length / 2)
    }
  }
}
</script>

<style>
.error {
  color: lightcoral;
}
.row {
  display: flex;
  margin: 10px;
}

.source {
  margin-right: 24px;
}

.column {
  display: flex;
  flex-flow: column nowrap;
  margin: 20px;
}
.textarea {
  width: 400px;
}
</style>

// app/renderer/ui/components/query/radonQuery/index.tsx
import * as React from "react"
import {
  RADRetrieveArgs,
  RADAggregateArgs,
  RADConsensusArgs,
} from "../../../../../common/runtimeTypes/wallet"

import { RadonScript } from "../../radonScript"
import {
  TYPES as RadonTypes,
  OPERATOR_INFOS as RadonOperatorInfos,
  HashFunctionCodes,
  ReducingFunctionCodes,
} from "../../../../radon"
import { match } from "app/renderer/utils/match"

const style = require("./style.scss")

export interface RadonQueryState {
  "retrieve": Array<RADRetrieveArgs>,
  "aggregate": RADAggregateArgs,
  "consensus": RADConsensusArgs,
}

export interface RadonQueryProps {
  className?: string,
  style?: string,
  request: {
    notBefore: number,
    retrieve: Array<{
      kind: string,
      url: string,
      script: Array<any>
    }>,
    aggregate: {
      script: Array<any>,
    },
    consensus: {
      script: Array<any>
    },
    deliver: Array<{
      kind: string,
      url: string,
    }>
  },
}

/**
 * RadonQuery UI component
 *
 * @export
 * @class RadonQuery
 * @extends {React.Component<RadonQuery>}
 */
export default class RadonQuery extends React.Component<RadonQueryProps, RadonQueryState> {
  public renderRetrieve = () => {
    const createSourceElement = (source: RADRetrieveArgs, index: number) => {
      return (
        <div className={style.column}>
          <label>source: {index} </label>
          <input
            placeholder="url"
            value={source.url}
            onChange={(event: React.ChangeEvent<HTMLInputElement>) => this.updateSource(event.target.value, index)}>
          </input>
          <div>
            <p>Kind: </p>
            <p>
              {source.kind}
            </p>

            <RadonScript
              path={{ stage: "retrieve", retrieveIndex: index }}
              radonScript={source.script}
              selectHashFunction={this.selectHashFunction}
              updateArgumentInput={this.updateArgumentInput}
              updateFilterArgument={this.updateFilterArgument}
              updateOperatorCodeSelect={this.updateOperatorCodeSelect}
              updateOperatorFilterArgument={this.updateOperatorFilterArgument}
              updateOperatorReduceArgument={this.updateOperatorReduceArgument}
            />
          </div>
        </div>
      )
    }

    return this.state.retrieve.map((source, index) => createSourceElement(source, index))
  }

  public updateSource = (url: string, sourceIndex: number) => {
    const retrieve = this.state.retrieve
    retrieve[sourceIndex].url = url
    this.setState({
      retrieve,
    })
  }

  public pushRetrieve = () => {
    const current = this.state.retrieve
    current.push({
      kind: "HTTP_GET",
      url: "",
      script: [],
    })
    this.setState({
      retrieve: current,
    })
  }

  public renderAggregate = () => {
    return (
      <div className={style.column}>
        <RadonScript
          path={{ stage: "aggregate" }}
          radonScript={this.state.aggregate.script}
          selectHashFunction={this.selectHashFunction}
          updateArgumentInput={this.updateArgumentInput}
          updateFilterArgument={this.updateFilterArgument}
          updateOperatorCodeSelect={this.updateOperatorCodeSelect}
          updateOperatorFilterArgument={this.updateOperatorFilterArgument}
          updateOperatorReduceArgument={this.updateOperatorReduceArgument}
        />
      </div>
    )
  }

  public renderConsensus = () => {
    return (
      <div className={style.column}>
        <RadonScript
          path={{ stage: "consensus" }}
          radonScript={this.state.consensus.script}
          selectHashFunction={this.selectHashFunction}
          updateArgumentInput={this.updateArgumentInput}
          updateFilterArgument={this.updateFilterArgument}
          updateOperatorCodeSelect={this.updateOperatorCodeSelect}
          updateOperatorFilterArgument={this.updateOperatorFilterArgument}
          updateOperatorReduceArgument={this.updateOperatorReduceArgument}
        />
      </div>
    )
  }

  public constructor(props: RadonQueryProps) {
    super(props)

    this.state = {
      retrieve: props.request.retrieve,
      aggregate: props.request.aggregate,
      consensus: props.request.consensus,
    }
  }
  public validateRadScript = (_: any) => {
    return false
  }

  public updateOperatorCodeSelect = (path: any, operatorCode: any) => {
    let args = RadonOperatorInfos[operatorCode].arguments
      .map((argument) => {
        return match(argument.kind, [
          { options: [RadonTypes.Boolean, RadonTypes.Int, RadonTypes.Float, RadonTypes.String,
            RadonTypes.FilterFunction],
          result: [argument.kind, ""] },
          { options: [RadonTypes.Map, RadonTypes.Mixed, RadonTypes.Array, RadonTypes.Null,
            RadonTypes.Result, RadonTypes.Self, RadonTypes.MapFunction],
          result: [] },
          { options: [RadonTypes.HashFunction],
            result: parseInt(parseInt(HashFunctionCodes[HashFunctionCodes[0]]).toString(16)) },
          { options: [RadonTypes.ReduceFunction],
            result: parseInt(parseInt(ReducingFunctionCodes[ReducingFunctionCodes[0]]).toString(16)) },
        ])
      })

    const newState: RadonQueryState = this.state
    if (path.stage === "retrieve") {
      newState[`${path.stage}`][path.retrieveIndex].script[path.scriptIndex] = [parseInt(operatorCode), ...args]

      if (!this.validateRadScript("")) {
        newState[`${path.stage}`][path.retrieveIndex]
          .script
          .splice(path.scriptIndex + 1, newState[`${path.stage}`][path.retrieveIndex].script.length)
      }
    } else {
      newState[`${path.stage}`].script[path.scriptIndex] = [parseInt(operatorCode), ...args]

      if (!this.validateRadScript("")) {
        newState[`${path.stage}`].script.splice(path.scriptIndex + 1, newState[`${path.stage}`].script.length)
      }
    }
    this.setState(newState)
  }

  public updateOperatorFilterArgument = (
    path: any,
    filterFunctionCode: number,
    operator: Array<any>,
    argIndex: number
  ) => {
    operator[argIndex] = [filterFunctionCode, ""]
    const newState = this.state
    if (path.retrieveIndex) {
      newState[`${path.stage}`][path.retrieveIndex][path.scriptIndex] = operator
    } else {
      newState[`${path.stage}`][path.scriptIndex] = operator
    }
    this.setState(newState)
  }

  private updateFilterArgument = (path: any, filterArgument: number, operator: Array<any>, argIndex: number) => {
    operator[argIndex] = [operator[argIndex][0], filterArgument]
    const newState = this.state
    if (path.retrieveIndex) {
      newState[`${path.stage}`][path.retrieveIndex][path.scriptIndex] = operator
    } else {
      newState[`${path.stage}`][path.scriptIndex] = operator
    }
    this.setState(newState)
  }

  private updateOperatorReduceArgument = (
    path: any,
    reduceArgument: number,
    operator: Array<any>,
    argIndex: number,
  ) => {
    operator[argIndex] = [operator[argIndex][0], reduceArgument]
    const newState = this.state
    if (path.retrieveIndex) {
      newState[`${path.stage}`][path.retrieveIndex][path.scriptIndex] = operator
    } else {
      newState[`${path.stage}`][path.scriptIndex] = operator
    }
    this.setState(newState)
  }

  private selectHashFunction = (path: any, hashFunctionCode: number, operator: Array<any>, argIndex: number) => {
    operator[argIndex] = hashFunctionCode
    const newState = this.state
    if (path.retrieveIndex) {
      newState[`${path.stage}`][path.retrieveIndex][path.scriptIndex] = operator
    } else {
      newState[`${path.stage}`][path.scriptIndex] = operator
    }
    this.setState(newState)
  }

  private updateArgumentInput = (path: any, input: any, operator: Array<any>, argIndex: number) => {
    operator[argIndex] = input
    const newState = this.state

    if (path.retrieveIndex) {
      newState[`${path.stage}`][path.retrieveIndex][path.scriptIndex] = operator
    } else {
      newState[`${path.stage}`][path.scriptIndex] = operator
    }
    this.setState(newState)
  }

  public render() {
    return (
      <div>
        <section className={style.section}>
          <div className={style.column}>
            <h1>Request</h1>
          </div>
          {this.renderRetrieve()}
          <div className={style.column}>
            <button onClick={this.pushRetrieve}>add source</button>
          </div>
        </section>
        <br></br>

        <section className={style.section}>
          <div className={style.column}>
            <h1>Aggregate</h1>
          </div>
          {this.renderAggregate()}
        </section>
        <br></br>

        <section className={style.section}>
          <div className={style.column}>
            <h1>Consensus</h1>
          </div>
          <div className={style.column}>
            {this.renderConsensus()}
          </div>
        </section>

        <section className={style.section}>
          <div className={style.column}>
            <h1>Deliver</h1>
          </div>
          <div className={style.column}>
            <input placeholder="url"></input>
          </div>
        </section>
      </div>
    )
  }
}
